### ISSUE TITLE
Clarify implications about the styling layer

### ISSUE THREAD

**Issue by KittyGiraudel** [Heydon/inclusive-menu-button#12]
I wonder if it would be worth clarifying the fact that the library does not make any consideration regarding styling at all, at that the entire CSS layer is left up to the author.

On that, maybe it would be better to remove aesthetics styles from the provided stylesheet (such as color and formatting) to leave only the bare minimum (position and visibility).

**Comment by Heydon** [comment]
@HugoGiraudel I went with functional styles only
