### ISSUE TITLE
Clarify origin/direction

### ISSUE THREAD

**Issue by KittyGiraudel** [Heydon/inclusive-menu-button#13]
In regards to the `data-menu-origin` option, I think it is worth mentioning that this is only used by the styling layer and that this is not used at all by the library itself. I would probably even remove it from the example (to keep it minimal), and add a section for that in the documentation. Right it feels like the library expects this very attribute while it’s just as good of a styling hook as anything else.

Side note, maybe `overflow-direction` might be a better name? What about using `start` and `end` to accomodate to RTL rather than `left` and `right`?

**Comment by Heydon** [comment]
Closing for now, as I've renamed it to `data-menu-from`.
