### ISSUE TITLE
Publish demo page

### ISSUE THREAD

**Issue by KittyGiraudel** [Heydon/inclusive-menu-button#18]
It would be nice to have a proper demo page with a few examples on how to use this library at its finest.

**Comment by 1j01** [comment]
Here are the demos on RawGit:

https://rawgit.com/Heydon/inclusive-menu-button/master/examples/basic.html
https://rawgit.com/Heydon/inclusive-menu-button/master/examples/disabled-items.html
https://rawgit.com/Heydon/inclusive-menu-button/master/examples/menuitemcheckbox.html
https://rawgit.com/Heydon/inclusive-menu-button/master/examples/menuitemradio.html

**Comment by 1j01** [comment]
You can [enable GitHub Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) pretty easily, for `master`; and then you can just link to these examples from the README. (Ideally there'd be a central page which you could link to as the website field of the repository (next to the description))
