### ISSUE TITLE
Implement event hooks

### ISSUE THREAD

**Issue by KittyGiraudel** [Heydon/inclusive-menu-button#3]
It would be nice to have some events which can be listened to when the menu gets opened or closed.

**Comment by Heydon** [comment]
@HugoGiraudel  I've dispatched a custom event with some detail properties that bubbles in this codePen: https://codepen.io/heydon/pen/9fd5cac1a6c23e25c9ffb8d5b3359b9c?editors=1010

I imagine there's some nuances / best practices for doing this that you'd suggest?

**Comment by KittyGiraudel** [comment]
I’ll have a look. ;)

**Comment by Heydon** [comment]
@HugoGiraudel Added a live region to that. Works nicely in VoiceOver...

**Comment by Heydon** [comment]
@HugoGiraudel My experiment so far isn't abstract enough because it's bound to the menu item's click event. Hmmm.

**Comment by KittyGiraudel** [comment]
I think we should go the same way a11y-dialog did. Register events on the instance with `.on()`, unbind them with `.off()`, and fire them with`._fire()` within `.open` and `.close` methods.

**Comment by Heydon** [comment]
I would have done if I understood how that worked :-P (I don't like to cargo cult stuff).

What's the underscore in `._fire()` for?

**Comment by KittyGiraudel** [comment]
Very sorry Heydon, didn’t want to sound botchy or pedantic. Alright, let me explain.

So the idea is that the user needs to be able to register event listeners on their `MenuButton` instance. To do so, inclusive-menu-button needs to provide `.on(…)` as part of its API. This method will save callbacks into a (private) property looking like this:

```js
this._listeners = {
  open: [ function () { … }, function () { … } ],
  close: [ function () { … } ]
}
```

Then when the menu gets opened or closed, each of the relevant registered listeners will be called.

The first thing we need to do is to define this empty object in the constructor of `MenuButton`:

```js
this._listeners = {}
```

Now the `.on` method, it might look like this:

```js
/**
 * Register a new callback for the given event type
 *
 * @param {string} type
 * @param {Function} handler
 */
MenuButton.prototype.on = function (type, handler) {
  if (typeof this._listeners[type] === 'undefined') {
    this._listeners[type] = []
  }

  this._listeners[type].push(handler)

  return this
}
```

This method accepts an event type as a string (like `open` for instance) and a function to execute when this event happens. All this method does is it pushes the new function into the `_listeners` property, in a key named after the event type (like `this._listeners.open`).

This allows the user to do that:

```js
const menu = new MenuButton(…)

menu.on('open', function () {
  // Do something
})
```

But right now, this given function is not executed anywhere. It is just saved in the instance listeners. We need to call it when opening the menu. This happens in the `.open` method.

```js
MenuButton.prototype.open = function () {
  this.button.setAttribute('aria-expanded', true)
  this.menu.hidden = false
  this.menuItems[0].focus()

  (this._listeners.open || []).forEach(function (listener) {
    listener()
  })

  return this
}
```

Here, we iterate over the registered listeners for the `open` event and call them. If we think it might be a good idea to pass some data to these listeners, this is also where we can do it. a11y-dialog passes the dialog DOM element for instance.

Now, we need the same thing in the `.close` method, but it’s a bit tedious having to repeat that boilerplate everywhere. So we can create a (private) method to call all registered listeners for a specific event. It would look like this:

```js
/**
 * Iterate over all registered handlers for given type and call them all with
 * the dialog element as first argument, trigger (opener / closer) as second
 * argument, if any.
 *
 * @access private
 * @param {string} type
 * @param {Event} event
 */
MenuButton.prototype._fire = function (type) {
  var listeners = this._listeners[type] || []

  listeners.forEach(function (listener) {
    listener()
  })
}
```

Then, we can update our `.open` method with:

```js
this._fire('open')
```

And do something similar in our `.close` method:

```js
this._fire('close')
```

The last thing we need to do is to provide a way for the user to unregister these listeners. This is where the `.off` method comes in. It needs an event type, and the function to unregister.

```js
/**
 * Unregister an existing callback for the given event type
 *
 * @param {string} type
 * @param {Function} handler
 */
MenuButton.prototype.off = function (type, handler) {
  var index = this._listeners[type].indexOf(handler)

  if (index > -1) {
    this._listeners[type].splice(index, 1)
  }

  return this
}
```

This can be used like this:

```js
menu.off('open', myOpenListener)
```

Now, all together:

```js
const menu = new MenuButton(…)

const myOpenListener = function () {
  console.log('Do something')
}

menu.on('open', myOpenListener)

// … later on

menu.off('open', myOpenListener)
```

Does it make more sense? :)

**Comment by Heydon** [comment]
So the underscore is to indicate it's a private method, I guess?

Thank you very much for the detailed explanation, very good design. I'll implement something like that.

For the record, I don't think you were being pedantic or anything. It was simply a statement of fact that I don't implement anything I don't understand (yet) as a matter of principle. You may have noticed that my code is typically quite minimal LOL but I think that's better than coding lots of stuff blind and creating a horrible insecure/buggy mess, which seems to be the fashion for inexpert JavaScript developers.

**Comment by KittyGiraudel** [comment]
> So the underscore is to indicate it's a private method, I guess?

Precisely. It really is just an indication. It does not make a property any private. But it’s common enough that it will indicate people that this is not meant to be used as part of the public API. They are welcome to do so if they need, but it might break from one day to the next.

> Thank you very much for the detailed explanation, very good design. I'll implement something like that.

Anytime. If I can help. :)

> It was simply a statement of fact that I don't implement anything I don't understand (yet) as a matter of principle.

Solid principle, I think it’s good. 

> that's better than coding lots of stuff blind and creating a horrible insecure/buggy mess, which seems to be the fashion for inexpert JavaScript developers.

Let’s not go this way… ;)

**Comment by Heydon** [comment]
I've implemented events in such a way that we can pass arbitrary data to the ._fire() method.

```js
 MenuButton.prototype._fire = function (type, data) {
    var listeners = this._listeners[type] || []
    var data = data || null

    listeners.forEach(function (listener) {
      listener(data)
    })
  }
```

For the select event, I pass an object with a couple of properties: 

```js
menuItem.addEventListener('click', function (e) {
    // pass data to select method
    this.select({
        elem: menuItem,
        label: menuItem.textContent          
    })
        
    // close menu and focus menu button
    this.close()
    this.button.focus()
  }.bind(this))
}.bind(this))
```

This is passed to `.fire()` in the select method:

```js
  MenuButton.prototype.select = function (data) {
    // fire open event
    this._fire('choose', data)

    return this
  }
```

So far the code is just in the codePen: https://codepen.io/heydon/pen/c4223ec051f82d3cc3e90214db816b88

Thoughts? :)

**Comment by KittyGiraudel** [comment]
I would advise against passing `null`; pass `data` if it exists, otherwise it will pass `undefined` which is fine. 

But the general gist is good yes. :)

Double checked the pen: it’s great!

**Comment by Heydon** [comment]
Sweet. I chose null because it's technically an object. Not sure what that helps with though.

Anyway, I figured this mechanism would be a good generic API feature to harness in future components.
