### ISSUE TITLE
Make it possible to pass custom selectors

### ISSUE THREAD

**Issue by KittyGiraudel** [Heydon/inclusive-menu-button#4]
Right now, the library expects `button` elements inside the menu. While correct (I think), it might be a bit restrictive. It would be nice to be able to pass a selector to query the menu items. Also, I think the default should rely on direct children rather than any arbitrary selector.

**Comment by Heydon** [comment]
@HugoGiraudel I think if they are going to be direct children, they should always be `<button>`. However, there's a case could be made that the menuitems should be containers for either `<button>`s or links. Although the arrow key + tabbing would be weird then.

**Comment by KittyGiraudel** [comment]
I think I disagree. If the menu is a `ul`, direct children will be `li`, which could contain `button` (or link, as you said). Defaulting on direct children, but being able to pass a selector seems like the most practical approach to me.

**Comment by Heydon** [comment]
@HugoGiraudel The thing is, `role="menuitem"` is not allowed to contain interactive children, apparently (just checked). So it has to be just a `menuitem`, which means it has to behave as a `menuitem`. Therefore, it can't contain a link. It could be a link _with_ `role="menuitem"`, but if it then behaves like a link, (screen reader) users would be confused.

We could have them as `<li>`, but as you suggested before, this would mean scripting the <kbd>Enter</kbd> and <kbd>Space</kbd> behavior.

**Comment by KittyGiraudel** [comment]
Alright, thank you for the clarification. I highly recommend being extremely clear about this in the documentation and examples then.

1. `role="menu"` should be a `div`
2. Its direct children should be `button`s
3. They should have `role="menuitem"`

Correct?

**Comment by Heydon** [comment]
@HugoGiraudel Yep! (Although the script adds that role currently) You've just reminded me, actually: I need to clarify about the CSS being terse in the README too.

**Comment by KittyGiraudel** [comment]
> Regarding supporting non-button element types as menuitems, I think we should just allow that or not, but it would mean scripting the Enter / Space key events of course.

This is kind of a tough call here. Either you want this library to be flexible, and we make it possible to have any kind of menu items, and script the event interaction if it’s not an interactive element just yet, or we enforce the usage of buttons as direct children. Is one better than the other semantically / from an AT perspective?

**Comment by Heydon** [comment]
The `menu` and `menuitem` roles take care of the semantics. 

The advantage of using `<button>`s is that the script is terser. Dispatching click events on Enter/Space is less robust than just using the underlying element behavior too. There are also concerns like disabled menuitems and their behavior. With `<button>` it's as simple as adding `disabled`. Mind you, I think I'd have to suppress arrow focus for that. Hurrah! A new thing to script.

**Comment by KittyGiraudel** [comment]
Then I’d say the easiest is to enforce direct children to be buttons. But I could see how v2 of the script comes back on this decision and allows more flexibility on the DOM structure.

So the README.md needs to be very clear about the expected structure to close this issue.

**Comment by KittyGiraudel** [comment]
Note: it would be nice to be able to use something than an ID. Anything preventing us from doing so (on a non-technical level I mean)?

**Comment by Heydon** [comment]
Not sure what you mean by "use something than an ID". Do you mean something other than the `data-inclusive-menu-opens` ID value to identify the menu?

**Comment by KittyGiraudel** [comment]
No I mean using `querySelector` rather than `getElementById`.

**Comment by Heydon** [comment]
It's kind of a convention for controlled elements to be associated by `id` (see `<label for="id">`, `aria-describedby="id"`, `aria-controls="id"` etc.)

The fact that multiple same `id`s are well known to be poor form (and come out as a parse error)  helps make sure the developer doesn't screw up.
