### ISSUE TITLE
Multiple buttons in the menu bar

### ISSUE THREAD

**Issue by ghost** [Heydon/inclusive-menu-button#42]
Hi.  I am reeeeeally new to javascript and I'm trawling repos for accessible menus to learn how to implement one.  I would like to use your menu system on my site - its the "nicest" one I've found - but I can't work out how to have more than one button.  Is it possible to have many buttons, each with options, or is the code limited to one button only?  Long-term, I guess I'm suggesting an example page with multiple buttons but short-term, a push in the right direction would be most appreciated. I'm happy to teach myself how but I just can't get started on this one!  PS: Love your work - its a really clean implementation from what I've seen so far!  Regards, Paul

**Comment by ghost** [comment]
Hi Hayden. I kept playing with the code and solved the problem!  I surprised myself a bit but that's the joys of javascript I guess.  Thanks for sharing your work. Regards, Paul

**Comment by Heydon** [comment]
@Paul-E-Matthews Sorry I missed your original comment. Glad you worked it out!

**Comment by ourcore** [comment]
@Heydon Could you please provide some documentation on programmatically instantiating multiple menu buttons? I've given mine unique `id`/`data-inclusive-menu-opens` values, but the ini code is only running on the first instance, unless I manually target each button. Thank you
