### ISSUE TITLE
Event duplication/memory bloat

### ISSUE THREAD

**Issue by sunnywalker** [Heydon/inclusive-menu-button#43]
Every time a menu is opened via its button, a new version of the `outsideClick()` event handler is attached to the `document`. This means that if a menu is opened twelve times, and a click is registered outside of the menu, there are now twelve calls to its `outsideClick()`. Add multiple menus and it gets worse, and if this is used for an application where the menus are used often between page loads, this can get ugly.

I'm trying to figure out how to get `removeEventListener()` to work from inside `outsideClick()` so it will de-register itself once it did its business but I've had no luck yet.

**Comment by Heydon** [comment]
@sunnywalker Thanks for letting me know!

**Comment by Heydon** [comment]
@sunnywalker Fixed (needed to use `removeEventListener` inside the `outsideClick() function, but bind this to that function)
