### ISSUE TITLE
Apple VoiceOver considers all menu items checked

### ISSUE THREAD

**Issue by sinisterstumble** [Heydon/inclusive-menu-button#44]
https://github.com/Heydon/inclusive-menu-button/blob/8c803a7e885f902f6d2e68deba1674881f1784e0/inclusive-menu-button.js#L209

Solved (at least for Apple VoiceOver) by

```js
menuItem.removeAttribute('aria-checked')
```

Is there a reason for not using `removeAttribute`?

Thank you!

**Comment by Heydon** [comment]
@15x Huh! Very good question. `removeAttribute` would make much more sense. Alternatively, it could be `setAttribute('aria-checked', 'false')` but there's no need for the attribute to be there at all in this case!

**Comment by Heydon** [comment]
@15x fixed, thanks again.
