### ISSUE TITLE
Fix documentation about data-inclusive-menu

### ISSUE THREAD

**Issue by KittyGiraudel** [Heydon/inclusive-menu-button#8]
The README states `data-inclusive-menu` is mandatory. It doesn’t seem to be. There is no trace of it in the code, and it only seems to be used for styling. I’d recommend we remove all traces of it, or make clear it is not a required attribute. :)

**Comment by Heydon** [comment]
@HugoGiraudel A container with `position: relative` and `display: inline-block` is needed here for the basic layout. It's required in the sense that it's used as a selector. Aside from that, I think it's nice for code organization i.e. "here be an inclusive menu thingy".
