### ISSUE TITLE
Use an options object for extensibility

### ISSUE THREAD

**Issue by KittyGiraudel** [Heydon/inclusive-menu-button#9]
This is likely that more options will be introduced in the future (see #4). Therefore I recommend passing an object to the constructor to make it easier to extend the API.

**Comment by Heydon** [comment]
I know _how_ to do this, but I'm wondering what folks might want to customize. Ideas:

* The left / right alignment of the menu
* Erm...

Regarding supporting non-button element types as `menuitem`s, I think we should just allow that or not, but it would mean scripting the Enter / Space key events of course.

**Comment by KittyGiraudel** [comment]
Regarding extensibility, you don’t really know where you library is going to go. Today, there might be no need for options, but maybe in the future there will be. This is a mistake I made in a11y-dialog; I should have started right away with accepting an object in the constructor. It will be the case in v4.

Let’s move the discussion about selectors in #4.

**Comment by Heydon** [comment]
Now handled for the `checkable` option.
